"""Project Mimic package entrypoint."""

from .environment import ProjectMimicEnv
from .engine import ClickDecision, ExecutionEngine
from .error_mapping import ErrorEnvelope, map_exception_to_error
from .identity import (
    IdentityAllocator,
    IdentityBundle,
    InMemoryProxyPoolStore,
    ProxyEndpoint,
    ProxyHealthEvent,
    RiskSignals,
    RotationAuditEvent,
    RotationReason,
    calculate_risk_score,
    should_rotate_identity,
)
from .grpc_runtime import (
    Ack,
    AnalyzeFrameRequest,
    AnalyzeFrameResponse,
    AttachSiteTaskRequest,
    CloseSessionRequest,
    CloseSessionResponse,
    CreateSessionRequest,
    CreateSessionResponse,
    EmitKeystrokesRequest,
    EmitPointerRequest,
    GroundActionRequest,
    GroundActionResponse,
    MimeticServiceHandler,
    NextStepRequest,
    NextStepResponse,
    OrchestratorServiceHandler,
    PlanKeystrokesRequest,
    PlanKeystrokesResponse,
    PlanPointerRequest,
    PlanPointerResponse,
    RequestMeta,
    SessionServiceHandler,
    VerifyStepRequest,
    VerifyStepResponse,
    VisionServiceHandler,
    build_default_grpc_runtime,
)
from .models import ActionType, ErrorCode, Observation, ProjectMimicModel, Reward, UIAction
from .mimetic import (
    JitterProfile,
    MimeticEvent,
    MimeticEventStream,
    MovementProfile,
    RustPythonEventBridge,
    TypoCorrectionStrategy,
    jitter_profile_for_device,
    movement_profile_for_viewport,
    plan_pointer_stream,
    synthesize_typing_stream,
)
from .observability import InMemoryMetrics, OpenTelemetryTracer, TraceSpan
from .policy import PolicyContext, PolicyDecision, PolicyEngine
from .queue_runtime import ActionJob, InMemoryActionQueue, JobStatus, WorkerLease
from .session_lifecycle import (
    InMemoryCheckpointStore,
    InvalidSessionTransitionError,
    RedisCheckpointStore,
    SessionExpiredError,
    SessionRegistry,
    SessionStatus,
)
from .tasks import TaskDefinition, TaskDifficulty, TaskEvidence, grade_task, task_catalog

__all__ = [
    "ActionType",
    "Ack",
    "AnalyzeFrameRequest",
    "AnalyzeFrameResponse",
    "AttachSiteTaskRequest",
    "ClickDecision",
    "CloseSessionRequest",
    "CloseSessionResponse",
    "CreateSessionRequest",
    "CreateSessionResponse",
    "EmitKeystrokesRequest",
    "EmitPointerRequest",
    "ErrorCode",
    "ErrorEnvelope",
    "ExecutionEngine",
    "GroundActionRequest",
    "GroundActionResponse",
    "IdentityAllocator",
    "IdentityBundle",
    "InMemoryProxyPoolStore",
    "Observation",
    "JitterProfile",
    "MimeticEvent",
    "MimeticEventStream",
    "MovementProfile",
    "MimeticServiceHandler",
    "NextStepRequest",
    "NextStepResponse",
    "InMemoryMetrics",
    "OpenTelemetryTracer",
    "InMemoryCheckpointStore",
    "InvalidSessionTransitionError",
    "InMemoryActionQueue",
    "JobStatus",
    "ProjectMimicEnv",
    "ProxyEndpoint",
    "ProxyHealthEvent",
    "PolicyContext",
    "PolicyDecision",
    "PolicyEngine",
    "PlanKeystrokesRequest",
    "PlanKeystrokesResponse",
    "PlanPointerRequest",
    "PlanPointerResponse",
    "ProjectMimicModel",
    "RiskSignals",
    "RotationAuditEvent",
    "RotationReason",
    "RedisCheckpointStore",
    "Reward",
    "RequestMeta",
    "RustPythonEventBridge",
    "OrchestratorServiceHandler",
    "SessionExpiredError",
    "SessionRegistry",
    "SessionServiceHandler",
    "SessionStatus",
    "TaskDefinition",
    "TaskDifficulty",
    "TaskEvidence",
    "TraceSpan",
    "TypoCorrectionStrategy",
    "UIAction",
    "ActionJob",
    "VerifyStepRequest",
    "VerifyStepResponse",
    "VisionServiceHandler",
    "WorkerLease",
    "build_default_grpc_runtime",
    "calculate_risk_score",
    "grade_task",
    "jitter_profile_for_device",
    "map_exception_to_error",
    "movement_profile_for_viewport",
    "plan_pointer_stream",
    "should_rotate_identity",
    "synthesize_typing_stream",
    "task_catalog",
]
